apiVersion: v1
kind: Service
metadata:
  name: example-service-active
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: example-service-preview
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000